Repository GammaStation/Gamma-Station, pull requests merged in 2018-10, with the labels that each got.

#252 госты могут смотреть содержимое ящиков
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Merge Ready

#223 Не все расы режутся об стекло, мусор etc.
  code/__DEFINES/flags.dm
  code/defines/obj/weapon.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/paperwork/paper.dm
  code/modules/scrap/scrap.dm
Labels: Tweak

#254 Удаляем дубликаты
  icons/obj/food.dmi
Labels: Merge Ready, Sprites

#231 Damp rag боьше не чистит одежду на мобе
  code/modules/detectivework/footprints_and_rag.dm
Labels: Merge Ready, Tweak

#260 Порт инвентаря с бейстейшен
  code/__DEFINES/inventory_sizes.dm
  code/defines/obj/weapon.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/briefcase.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/storage/internal.dm
  code/game/objects/items/weapons/storage/lockbox.dm
  code/game/objects/items/weapons/storage/secure.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/items/weapons/storage/storage_ui/default.dm
  code/game/objects/items/weapons/storage/storage_ui/storage_ui.dm
  code/game/objects/items/weapons/storage/toolbox.dm
  code/game/objects/items/weapons/storage/wallets.dm
  code/game/objects/structures/inflatable.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/accessories/storage.dm
  code/modules/projectiles/guns/projectile/pneumatic.dm
  code/modules/research/xenoarchaeology/finds/finds.dm
  code/modules/research/xenoarchaeology/tools/tools.dm
  code/modules/research/xenoarchaeology/tools/tools_pickaxe.dm
  code/modules/scrap/oldificator.dm
  code/modules/scrap/scrap.dm
  code/modules/scrap/scrap_tools.dm
  icons/mob/screen1.dmi
  taucetistation.dme
Labels: Feature, Merge Ready, Sprites

#243 Анимация пикапа и путдауна предметов.
  code/game/objects/items.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/mob/inventory.dm
  code/modules/recycling/disposal.dm
Labels: Feature, Merge Ready

#270 Быстрофикс после инвентаря
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/secure.dm
  code/modules/scrap/scrap_tools.dm
Labels: Merge Ready

#268 Stool resprite
  icons/obj/objects.dmi
Labels: Sprites

#279 IPC heads
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites

#271 Your memes ends here
  code/__DEFINES/role_preferences.dm
  code/_globalvars/lists/misc.dm
  code/controllers/configuration.dm
  code/datums/mind.dm
  code/game/gamemodes/meme/meme.dm
  code/game/gamemodes/objective.dm
  code/modules/admin/admin.dm
  code/modules/admin/player_panel.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/parasite/meme.dm
  code/modules/mob/living/parasite/parasite.dm
  taucetistation.dme
Labels: Fix, Global Problems, Priority: CRITICAL, Revert / Removal

#280 Можно красить мехов и боргов
  code/game/objects/items/crayons.dm
Labels: Merge Ready

#263 Эпопея рефакторинга, часть первая: машинерия и оружие
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/chemistry/machinery/coda_dispencer.dm
  code/modules/reagents/chemistry/machinery/pandemic.dm
  code/modules/reagents/chemistry/machinery/reagent_grinder.dm
  code/modules/reagents/chemistry/weaponry/dartgun.dm
  code/modules/reagents/chemistry/weaponry/grenade_launcher.dm
  code/modules/reagents/chemistry/weaponry/syringe_gun.dm
Labels: Merge Ready

#259 Science goggles теперь полезные
  code/game/atoms.dm
  code/game/objects/items/robot/robot_items.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/research/designs.dm
  code/modules/research/xenoarchaeology/misc.dm
  maps/z1.dmm
  maps/z5.dmm
Labels: Feature, Merge Ready

#235 Различные типы атаки у хуманов.
  code/_onclick/click.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  code/modules/mob/living/carbon/alien/alien_defense.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/ian/ian.dm
  code/modules/mob/living/carbon/metroid/metroid.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  icons/mob/screen1_action.dmi
  icons/mob/unarmed_sel.dmi
  interface/skin.dmf
Labels: Feature, Merge Ready, Sprites

#306 Братишка, я тебе фиксов принёс 2
  code/game/objects/structures/tables_racks.dm
  code/modules/mob/living/carbon/brain/MMI.dm
  icons/obj/assemblies.dmi
  maps/z2.dmm
Labels: Map Edit, Sprites

#297 Разбивание стакана при броске
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
Labels: Merge Ready

#317 Ликвидирован спам логами у хайвмайнда тенелингов
  code/game/gamemodes/shadowling/shadowling_abilities.dm
Labels: Fix

#313 Agrevol, когда карта?
  code/game/area/Space Station 13 areas.dm
  maps/templates/holodeck/basketball.dmm
  maps/templates/holodeck/courtroom.dmm
  maps/templates/holodeck/emptycourt.dmm
  maps/templates/holodeck/meetinghall.dmm
  maps/templates/holodeck/picnicarea.dmm
  maps/templates/holodeck/theatre.dmm
  maps/templates/holodeck/thunderdomecourt.dmm
  maps/z1.dmm
Labels: Map Edit

#320 Welpie
  code/modules/locations/centcomm/monitor_90.dmi
  icons/obj/decals.dmi
Labels: Sprites

#314 Чистим silicon'ов от говнокода
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/decoy/life.dm
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/drone/drone_console.dm
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
  code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
  code/modules/mob/living/silicon/robot/drone/maintenance.dm
  code/modules/mob/living/silicon/robot/examine.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/silicon.dm
  taucetistation.dme
Labels: Code Improvements, Fix, Merge Ready

#325 da
  code/modules/locations/centcomm/monitor_90.dmi
Labels: Sprites

#326 фиксы карты
  maps/z1.dmm
Labels: Map Edit

#329 Зафиксил потерявшиеся айконстейты
  icons/obj/closet.dmi
Labels: Sprites

#330 Продолжаем фиксить потерянные спрайты
  icons/mob/uniform.dmi
  icons/obj/closet.dmi
Labels: Sprites

#331 Фиксы карты
  maps/z1.dmm
Labels: Map Edit

#332 Мапфиксы+спрайтфиксы
  code/modules/locations/centcomm/monitor_90.dmi
  maps/z1.dmm
Labels: Map Edit, Sprites

#337 Картоправки
  maps/z1.dmm
Labels: Map Edit

#344 Багфиксы карты и голодека
  maps/templates/holodeck/emptycourt.dmm
  maps/z1.dmm
Labels: Map Edit

#349 Чиним проебанные спавнпоинты
  maps/z1.dmm
Labels: Map Edit

#350 Марио, ты ли это?
  maps/z1.dmm
Labels: Map Edit

#347 [WIP] Респрайт охраны
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  icons/mob/belt.dmi
  icons/mob/eyes.dmi
  icons/mob/hands.dmi
  icons/mob/head.dmi
  icons/mob/mask.dmi
  icons/mob/robots.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/closet.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites, Work In Progress

#354 yet another mapfix
  maps/z1.dmm
Labels: Map Edit
