Repository GammaStation/Gamma-Station, pull requests merged in 2018-07, with the labels that each got.

#16 Фикс спрайтов гидропоники
  code/defines/obj/hydro.dm
  code/game/machinery/hydroponics.dm
  code/modules/research/xenoarchaeology/genetics/prehistoric_plants.dm
  icons/obj/hydroponics/growing.dmi
  icons/obj/hydroponics/growing_ancients.dmi
  icons/obj/hydroponics/hydroponics.dmi
Labels: Fix, Sprites

#17 Фиксы с классики
  code/game/gamemodes/cult/cult_datums.dm
  code/game/gamemodes/shadowling/shadowling_abilities.dm
  code/modules/admin/admin_investigate.dm
  code/modules/mob/language.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/species.dm
Labels: Fix, Tweak

#18 CentComm shuttle area remap
  maps/z2.dmm
Labels: Map Edit

#19 Hulk tweaks
  code/game/dna/genes/powers.dm
  code/modules/mob/living/simple_animal/hulk.dm
Labels: Tweak

#20 Cigarettes remade&resprited
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/random/random_misc.dm
  code/modules/cargo/packs.dm
  icons/obj/cigarettes.dmi
  maps/z1.dmm
Labels: Map Edit, Sprites

#24 Исправлена 71 строчка в файле style.css
  config/rules/style.css
Labels: Fix

#25 Мелкие исправления вида страницы с правилами
  config/rules/rules.html
  config/rules/style.css
Labels: Feature

#27 Paramedic acceess to surgery
  code/game/jobs/job/medical.dm
Labels: Tweak

#28 Временное барахло для щитспавна
  code/game/objects/event_items/armor.dmi
  code/game/objects/event_items/doom.dm
  code/game/objects/event_items/gunz.dm
  code/game/objects/event_items/gunz.dmi
  code/modules/mob/living/simple_animal/hostile/events_misc.dm
  icons/mob/hellspawn.dmi
  sound/event/demon_death.wav
  sound/event/gazer_shot.wav
  sound/event/stryker_shot.wav
  taucetistation.dme
Labels: Sprites

#29 Добавлен конфиг для выключения халков
  code/__DEFINES/genetics.dm
  code/controllers/configuration.dm
  code/game/dna/genes/powers.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  config/example/config.txt
Labels: Tweak

#33 Фикс парамедиков и вирусологов
  maps/z1.dmm
  maps/z2.dmm
Labels: Fix, Map Edit

#32 Species shown in examine
  code/modules/mob/living/carbon/human/examine.dm
Labels: Tweak

#36 Убрал лишнее из зоны ферриЦК шаттла
  maps/z2.dmm
Labels: Map Edit

#38 New IPC screens w/ colours
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites

#40 Увеличил время, которое требуется на ответственные профессии
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/silicon.dm
Labels: Tweak

#41 Ограничение по количеству выдаваемых денег в банкомате by Klpghf
  code/modules/economy/ATM.dm
Labels: Fix

#44 Теперь трубы для передачи тепла передают тепло.
  code/modules/atmospheric/machinery/components/unary_devices/heat_exchanger.dm
Labels: Fix, Global Problems, Priority: CRITICAL

#45 M66 кевларовая броня получила нормальную защиту.
  code/game/objects/WalterJ_Items_Pack/NT PMC/WJ_NT_PMC.dm
Labels: Balance

#46 Ботинки PMC получили защиту от подскальзываний.
  code/game/objects/WalterJ_Items_Pack/NT PMC/WJ_NT_PMC.dm
Labels: Balance

#50 Фикс вечноломающихся канистр.
  code/modules/atmospheric/machinery/portable/canister.dm
Labels: Fix

#13 Подушки безопасности
  code/game/objects/items/airbag.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/atmospheric/ZAS/Airflow.dm
  code/modules/research/designs.dm
  icons/obj/items.dmi
  taucetistation.dme
Labels: Feature, Sprites

#57 Теперь в Body Scanner можно Drag and Drop'ать пациентов.
  code/game/machinery/adv_med.dm
Labels: Tweak

#58 Исправил слышимость эссенциями всего происходящего в мире, исправил н…
  code/game/gamemodes/changeling/powers/essences.dm
  code/modules/mob/living/carbon/human/say.dm
Labels: Tweak

#59 Понерфлен голодамаг от атмоса в два раза.
  code/modules/atmospheric/ZAS/Airflow.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: Balance

#62 Banhub
  interface/interface.dm
  interface/skin.dmf
Labels: Feature

#67 Дегрифизация фороновых построек
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_types.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/turfs/simulated/walls_mineral.dm
  code/modules/atmospheric/xgm/gases.dm
Labels: Tweak

#66 Бронежилеты и шлема для ОБР.
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#63 Спрайты растений и камней с маринесов
  code/game/objects/structures/flora.dm
  icons/obj/flora/jungletrees.dmi
  icons/obj/flora/jungletreesmall.dmi
  icons/obj/flora/largejungleflora.dmi
Labels: Sprites

#70 Новые эмодзи.
  code/modules/goonchat/browserassets/css/emoji.css
  code/modules/goonchat/browserassets/css/emoji/at.png
  code/modules/goonchat/browserassets/css/emoji/cat.png
  code/modules/goonchat/browserassets/css/emoji/crash.png
  code/modules/goonchat/browserassets/css/emoji/dpepe.gif
  code/modules/goonchat/browserassets/css/emoji/duck.png
  code/modules/goonchat/browserassets/css/emoji/flash.png
  code/modules/goonchat/browserassets/css/emoji/glul.png
  code/modules/goonchat/browserassets/css/emoji/happyman.png
  code/modules/goonchat/browserassets/css/emoji/honk.png
  code/modules/goonchat/browserassets/css/emoji/jerry.png
  code/modules/goonchat/browserassets/css/emoji/kek.png
  code/modules/goonchat/browserassets/css/emoji/lul.png
  code/modules/goonchat/browserassets/css/emoji/ohmycat.png
  code/modules/goonchat/browserassets/css/emoji/peka.png
  code/modules/goonchat/browserassets/css/emoji/peka1.png
  code/modules/goonchat/browserassets/css/emoji/peka2.png
  code/modules/goonchat/browserassets/css/emoji/pekaanon.png
  code/modules/goonchat/browserassets/css/emoji/pekabaton.png
  code/modules/goonchat/browserassets/css/emoji/pekabloody.png
  code/modules/goonchat/browserassets/css/emoji/pekadoom.png
  code/modules/goonchat/browserassets/css/emoji/pekagachi.png
  code/modules/goonchat/browserassets/css/emoji/pekahmm.png
  code/modules/goonchat/browserassets/css/emoji/pekainsanededadvice.png
  code/modules/goonchat/browserassets/css/emoji/pekamorcrate.png
  code/modules/goonchat/browserassets/css/emoji/pekamrazish.png
  code/modules/goonchat/browserassets/css/emoji/pekaolt.png
  code/modules/goonchat/browserassets/css/emoji/pekapepe.png
  code/modules/goonchat/browserassets/css/emoji/pekarage.png
  code/modules/goonchat/browserassets/css/emoji/pekaragec.png
  code/modules/goonchat/browserassets/css/emoji/pekarp.png
  code/modules/goonchat/browserassets/css/emoji/pekasmart.png
  code/modules/goonchat/browserassets/css/emoji/pekaspace.png
  code/modules/goonchat/browserassets/css/emoji/pekathink.png
  code/modules/goonchat/browserassets/css/emoji/pepeamazing.png
  code/modules/goonchat/browserassets/css/emoji/pepecop.png
  code/modules/goonchat/browserassets/css/emoji/pepecross.png
  code/modules/goonchat/browserassets/css/emoji/pepecry.png
  code/modules/goonchat/browserassets/css/emoji/pepedamn.png
  code/modules/goonchat/browserassets/css/emoji/pepedetectiv.png
  code/modules/goonchat/browserassets/css/emoji/pepefeelsup.png
  code/modules/goonchat/browserassets/css/emoji/pepehmm.png
  code/modules/goonchat/browserassets/css/emoji/pepejoy.png
  code/modules/goonchat/browserassets/css/emoji/pepelove.png
  code/modules/goonchat/browserassets/css/emoji/pepemanok.png
  code/modules/goonchat/browserassets/css/emoji/peperage.png
  code/modules/goonchat/browserassets/css/emoji/pepesalut.png
  code/modules/goonchat/browserassets/css/emoji/pepesur.png
  code/modules/goonchat/browserassets/css/emoji/pepewhat.gif
  code/modules/goonchat/browserassets/css/emoji/pepewhy.png
  code/modules/goonchat/browserassets/css/emoji/pepewow.png
  code/modules/goonchat/browserassets/css/emoji/peporage.png
  code/modules/goonchat/browserassets/css/emoji/pominki.png
  code/modules/goonchat/browserassets/css/emoji/shrug.png
  code/modules/goonchat/browserassets/css/emoji/soqa.png
  code/modules/goonchat/browserassets/css/emoji/think.gif
  code/modules/goonchat/browserassets/css/emoji/thinkgun.png
  code/modules/goonchat/browserassets/css/emoji/topbestever.png
  code/modules/goonchat/browserassets/css/emojib64.css
  code/modules/goonchat/browserassets/js/emojiList.json
Labels: Fix, Sprites

#72 Донатерам добавлена возможность менять иконку госта.
  code/modules/mob/dead/observer/observer.dm
  icons/mob/donators.dmi
Labels: Sprites, Tweak

#71 При вхождении в криостазис в мед. рекордсах будет пометка, что у косм…
  code/game/machinery/cryopod.dm
Labels: Feature

#74 Исправлен спрайт для фальшивого шлема синдиката.
  code/modules/clothing/head/misc.dm
Labels: Fix

#77 рефактор воздействия очков на космонавта. Добавление переменной flash_protection, Избавление от путаницы в ХУД очках.
  code/_globalvars/misc.dm
  code/game/gamemodes/changeling/powers/essences.dm
  code/game/gamemodes/heist/heist_prices.dm
  code/game/gamemodes/shadowling/shadowling.dm
  code/game/gamemodes/shadowling/shadowling_abilities.dm
  code/game/gamemodes/shadowling/shadowling_items.dm
  code/game/jobs/job/security.dm
  code/game/objects/items/devices/flash.dm
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/items/weapons/tools.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/admin/verbs/debug.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/spacesuits/Skafandr_kosmicheskiy.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/mining/scanners.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/research/designs.dm
  code/modules/scrap/oldificator.dm
  maps/z2.dmm
Labels: Balance, Feature, Map Edit

#87 Фикс фальшстен
  code/game/objects/structures/false_walls.dm
Labels: Fix

#92 Ксеносы оперативники получили свою пару ботинок.
  code/game/gamemodes/nuclear/nuclear.dm
  code/modules/clothing/shoes/miscellaneous.dm
Labels: Tweak

#89 Рекс и Полкан возвращаются на ЦК.
  maps/z2.dmm
Labels: Map Edit, Tweak

#82 Лампы в морге мигают зеленым если внутри тела есть игрок
  code/game/objects/structures/morgue.dm
  icons/obj/stationobjs.dmi
Labels: Feature, Sprites

#93 Радшторм не затрагивает СПУ
  code/datums/weather/weather_types.dm
Labels: Fix
