Repository GammaStation/Gamma-Station, pull requests merged in 2018-09, with the labels that each got.

#167 Предметы из голодека теперь не вынести в оберточной бумаге
  code/modules/holodeck/HolodeckControl.dm
Labels: Fix

#170 Упаковочная бумага игнорирует предметы из голодека
  code/game/objects/items/weapons/gift_wrappaper.dm
  code/modules/recycling/sortingmachinery.dm
Labels: Fix

#172 Война с голодеком, ч.3
  code/modules/holodeck/HolodeckObjects.dm
  maps/templates/holodeck/courtroom.dmm
  maps/templates/holodeck/picnicarea.dmm
Labels: Fix, Map Edit

#176 Теперь наручники из кабелей делаются по-человечески
  code/game/objects/items/stacks/stack.dm
  code/modules/power/cable.dm
Labels: Tweak

#171 Revposter fixes
  code/game/objects/effects/decals/contraband.dm
Labels: Fix, Merge Ready, Sprites

#184 Краду паранормальные вещи.
  code/defines/obj/weapon.dm
  code/game/gamemodes/cult/ritual.dm
  code/game/machinery/hydroponics.dm
  code/game/machinery/vending.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/weapons/dice.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/modules/flufftext/Dreaming.dm
  code/modules/food/recipes_microwave.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/living/simple_animal/shade.dm
  code/modules/paperwork/pen.dm
  code/modules/paperwork/photography.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/research/xenoarchaeology/finds/finds_special.dm
  maps/z1.dmm
  maps/z3.dmm
Labels: Map Edit

#186 Поменял время. Once again
  code/_globalvars/lists/misc.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/silicon.dm
Labels: Balance

#188 хотфикс
  maps/z1.dmm
Labels: Map Edit

#190 No peka in IC
  code/modules/mob/living/say.dm
Labels: Global Problems, Merge Ready, Priority: CRITICAL

#173 Фикс кластербенгов
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/items/weapons/grenades/spawnergrenade.dm
Labels: Fix, Merge Ready

#168 Walktoggle removed from targeting victim
  code/modules/projectiles/targeting.dm
Labels: Tweak

#200 Hotfixing paranormal port.
  code/modules/reagents/Chemistry-Reagents.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/items.dmi
Labels: Sprites

#204 Пытаемся пережить послеэффект выпила перчаток.
  code/__DEFINES/flags.dm
  code/game/atoms.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/scrap/scrap.dm
Labels: Feature, Tweak

#207 Флора
  code/game/objects/structures/flora.dm
  icons/obj/flora/jungleflora.dmi
  icons/obj/flora/rocks.dmi
Labels: Sprites

#205 Laser scalpels
  code/modules/research/designs.dm
  code/modules/surgery/generic.dm
Labels: Balance, Fix

#102 Полезная вирусология + Зомби вирус
  code/__DEFINES/flags.dm
  code/__DEFINES/mob.dm
  code/datums/datumvars.dm
  code/modules/admin/admin_verbs.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/human/whisper.dm
  code/modules/mob/living/carbon/human/zombie.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/organs/organ_external.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/virus2/analyser.dm
  code/modules/virus2/disease2.dm
  code/modules/virus2/diseasesplicer.dm
  code/modules/virus2/dishincubator.dm
  code/modules/virus2/effect.dm
  code/modules/virus2/helpers.dm
  code/modules/virus2/items_devices.dm
  icons/effects/blood.dmi
  icons/effects/species.dmi
  icons/mob/human_races/r_zombie.dmi
  icons/mob/human_races/r_zombie_lizard.dmi
  icons/mob/human_races/r_zombie_skrell.dmi
  icons/mob/human_races/r_zombie_tajaran.dmi
  maps/z1.dmm
  nano/templates/disease_splicer.tmpl
  nano/templates/dish_incubator.tmpl
  taucetistation.dme
Labels: Feature, Map Edit, Sprites

#213 Тени не должны и не страдают кретинизмом, а так же убрал органы для м…
  code/game/gamemodes/shadowling/special_shadowling_abilities.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/species.dm
Labels: Balance

#222 LiptonPain
  icons/mob/suit.dmi
Labels: Sprites

#225 Обновление причёсок
  icons/mob/human_face.dmi
Labels: Sprites

#226 Вернул спрайт супу из слайма
  icons/obj/food.dmi
Labels: Sprites

#227 Мед. пояс теперь вмещает масс-спектрометр и сканнер реагентов
  code/game/objects/items/weapons/storage/belt.dm
Labels: Fix

#160 Helmet bands
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/cargo/exports/gear.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/head/helmet.dm
  code/modules/mining/mining_fabricator/mining_research.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/head.dmi
  icons/mob/helmet_bands.dmi
  maps/z1.dmm
  maps/z2.dmm
Labels: Feature, Map Edit, Sprites

#220 Фиксы гнилых респрайтов
  code/__DEFINES/mob.dm
  code/__HELPERS/game.dm
  code/game/mecha/medical/odysseus.dm
  code/game/objects/items.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/zombie.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/silicon/pai/hud.dm
  code/modules/organs/blood.dm
  code/modules/organs/organ.dm
  code/modules/organs/organ_external.dm
  code/modules/recycling/disposal.dm
  code/modules/virus2/disease2.dm
  code/modules/virus2/helpers.dm
  icons/mob/human_races/r_zombie.dmi
Labels: Fix, Merge Ready, Sprites

#215 Последний удар по пекам
  code/game/verbs/ooc.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/admin/verbs/adminsay.dm
  code/modules/admin/verbs/staffhelp.dm
  code/modules/goonchat/browserOutput.dm
  code/modules/goonchat/browserassets/js/browserOutput.js
  code/modules/mob/emote.dm
  code/modules/mob/mob.dm
  code/modules/mob/say.dm
Labels: Merge Ready, Revert / Removal

#246 Телепортоабуз NO MORE
  code/game/machinery/teleporter.dm
  code/game/objects/items/weapons/teleportation.dm
Labels: Fix

#247 Разрешены эмодзи в ЛООК
  code/game/verbs/ooc.dm
Labels: Fix, Merge Ready

#239 Хирургия СПУ. Фиксы.
  code/game/objects/items/stacks/nanopaste.dm
  code/modules/surgery/other.dm
  code/modules/surgery/ribcage.dm
  code/modules/surgery/robolimbs.dm
Labels: Fix, Merge Ready

#212 No NarSie for you
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/cult/cult_datums.dm
Labels: Balance, HONK, Merge Ready

#244 Новый плейлист в джукбокс
  code/modules/media/jukebox.dm
Labels: Feature, Merge Ready

#185 Changeling stasis fix
  code/game/gamemodes/changeling/headcrab.dm
  code/game/gamemodes/changeling/powers/revive.dm
Labels: Fix, Merge Ready

#253 Тащим причёски с Парадайзов
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites

#255 Хотфикс
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites
