Repository GammaStation/Gamma-Station, pull requests merged in 2018-12, with the labels that each got.

#529 - Тихеонский риг нельзя найти на помойке.
  code/game/objects/random/random_cloth.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/cargo/supplyshuttle.dm
  code/modules/recycling/disposal.dm
Labels: Fix, Merge Ready

#530 Спрайт PTR-7 на спине и фикс описания скафандра.
  code/modules/clothing/clothing.dm
  icons/mob/back.dmi
Labels: Fix, Merge Ready, Sprites

#182 Smg2049
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
  sound/weapons/guns/type76_reload.ogg
  sound/weapons/guns/type76_shot.ogg
Labels: Feature, Fix, Merge Ready, Sprites

#539 Новая пушка для хоса
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/projectiles/guns/energy/bison.dm
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/gun.dmi
  taucetistation.dme
Labels: Balance, Feature, Merge Ready, Sprites

#538 Рефактор работы action_button
  code/_onclick/hud/action.dm
  code/game/gamemodes/abduction/abduction_gear.dm
  code/game/gamemodes/shadowling/shadowling_items.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/flash.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/devices/megaphone.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/devices/taperecorder.dm
  code/game/objects/items/devices/whistle.dm
  code/game/objects/items/weapons/RCD.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/defibrillator.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/scrolls.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/tanks/jetpack.dm
  code/game/objects/items/weapons/tanks/watertank.dm
  code/game/objects/items/weapons/tools.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/clothing/spacesuits/globose.dm
  code/modules/clothing/spacesuits/rig.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/holidays/new_year/clothing.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/projectiles/gun.dm
  code/modules/reagents/reagent_containers/food/glowsticks.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/scrap/scrap_light.dm
Labels: Experimental, Merge Ready, Refactor

#542 Понижаем громкость шлюзов
  code/game/machinery/doors/door.dm
Labels: Merge Ready, Tweak

#544 Спрайты для М79 и RiotGun
  icons/mob/back.dmi
  icons/mob/belt_mirror.dmi
Labels: Merge Ready, Sprites

#547 Обновил проводку в ВиАр руме
  maps/z1.dmm
Labels: Map Edit, Merge Ready

#548 Call nerf от одного странника
  code/_onclick/hud/action.dm
  code/game/gamemodes/events/ninja_equipment.dm
  code/game/objects/effects/mines.dm
  code/modules/admin/verbs/modifyvariables.dm
  code/modules/maps/maps_code/wildwest.dm
Labels: Fix, Merge Ready, Refactor

#550 В основном рефакторы я даже не могу сказать какие баги пофиксил.
  code/_onclick/telekinesis.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/objects/items/stacks/rods.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/mob.dm
  code/modules/orbit/orbit.dm
Labels: Merge Ready, Refactor

#553 Быстрофикс дверей клоуна.
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/windowdoor.dm
Labels: Fix, Merge Ready

#556 Фикс двух роковых строчек
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
Labels: Fix, Merge Ready

#557 Последний фикс ~~пипетки~~ шлюзов.
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/windowdoor.dm
Labels: Fix, Merge Ready

#558 Thunder fix part tree
  code/modules/thunderfield2562/thunderfield_gamepod.dm
Labels: Balance, Merge Ready

#562 Улучшение дронов + фикс модулей.
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Balance, Fix, Merge Ready, Tweak

#564 Пиратская повязка с ХУДом
  code/modules/client/character menu/loadout/loadout_glasses.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/hud.dm
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Feature, Merge Ready, Sprites

#567 Мелкие фиксы телекинетического одеяния вещей на себя.
  code/game/objects/items/devices/radio/intercom.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/paperwork/photography.dm
Labels: Fix, Merge Ready

#576 фикс фикса возможности класть издалека
  code/game/objects/items/weapons/storage/storage.dm
Labels: Fix, Merge Ready

#555 Action buttons ressurection
  code/_onclick/hud/action.dm
  code/game/gamemodes/abduction/abduction_gear.dm
  code/game/gamemodes/shadowling/shadowling_items.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/flash.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/devices/megaphone.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/devices/taperecorder.dm
  code/game/objects/items/devices/whistle.dm
  code/game/objects/items/weapons/RCD.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/defibrillator.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/scrolls.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/tanks/jetpack.dm
  code/game/objects/items/weapons/tanks/watertank.dm
  code/game/objects/items/weapons/tools.dm
  code/modules/admin/verbs/massmodvar.dm
  code/modules/admin/verbs/modifyvariables.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/clothing/spacesuits/globose.dm
  code/modules/clothing/spacesuits/rig.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/holidays/new_year/clothing.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/projectiles/gun.dm
  code/modules/reagents/reagent_containers/food/glowsticks.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/scrap/scrap_light.dm
Labels: Experimental, Merge Ready, SQUASH

#603 hairfix
  icons/mob/human_face.dmi
Labels: Sprites

#210 Добавление отдельного сабсистема для денежных счетов
  code/__DEFINES/subsystem.dm
  code/controllers/subsystem/economy.dm
  code/controllers/subsystem/jobs.dm
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/scoreboard.dm
  code/game/machinery/vending.dm
  code/game/machinery/vendshop.dm
  code/game/objects/structures/watercloset.dm
  code/modules/economy/ATM.dm
  code/modules/economy/Accounts.dm
  code/modules/economy/Accounts_DB.dm
  code/modules/economy/EFTPOS.dm
  code/modules/economy/Events.dm
  code/modules/economy/TradeDestinations.dm
  code/modules/economy/economy_misc.dm
  code/modules/events/money_hacker.dm
  code/modules/events/money_lotto.dm
  code/modules/thunderfield2562/thunderfield_gamepod.dm
  taucetistation.dme
Labels: Merge Ready, Performance

#607 Fixes #605
  code/game/objects/items.dm
  code/modules/mob/inventory.dm
Labels: Fix, Merge Ready, SQUASH

#593 Отключено логирование у серверов связи
  code/game/machinery/telecomms/telecomunications.dm
Labels: Experimental, Merge Ready, Performance, Tweak

#610 Hotfixing #609
  code/game/objects/items/weapons/storage/storage.dm
Labels: Fix, Merge Ready

#614 Фиксы спрайтов ОЧКОв
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Fix, Merge Ready, SQUASH, Sprites

#604 Holomaps
  code/__DEFINES/flags.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/action.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  code/controllers/subsystem/ticker.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/ert.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/holomaps/holochip.dm
  icons/holomaps/canvas.dmi
  icons/holomaps/holochips.dmi
  icons/holomaps/holomap_markers.dmi
  taucetistation.dme
Labels: Feature, Merge Ready, SQUASH, Sprites

#624 Hotfixes
  code/_onclick/hud/action.dm
  code/modules/clothing/spacesuits/rig.dm
Labels: Fix

#631 фикс рцд
  code/game/objects/items/weapons/RCD.dm
Labels: Fix, Merge Ready

#630 Spacepod
  code/game/area/Space Station 13 areas.dm
  code/modules/mining/mine_items.dm
  code/modules/spacepods/spacepoddoor.dm
  icons/obj/survival_pod.dmi
  icons/turf/floors.dmi
  maps/z1.dmm
Labels: Map Edit, Merge Ready, Sprites

#634 Фикс анимации подъёма предметов.
  code/modules/mob/inventory.dm
Labels: Fix, Merge Ready

#581 Фикс того, что бумага не защищала от телепатии.
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Fix, Merge Ready

#602 Языковые воздействия на кукол.
  code/modules/mob/hear_say.dm
  code/modules/mob/language.dm
  code/modules/mob/living/carbon/species.dm
Labels: Test Merge

#644 pre-ngmapfixes
  maps/z1.dmm
Labels: Map Edit, Merge Ready

#641 Фиксы гнилых рантаймов
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/surgery/braincore.dm
  code/modules/surgery/other.dm
  code/modules/surgery/ribcage.dm
  code/modules/surgery/surgery.dm
Labels: Fix, Merge Ready
