Repository GammaStation/Gamma-Station, pull requests merged in 2018-11, with the labels that each got.

#366 E.V.A. Remap
  maps/z1.dmm
Labels: Map Edit

#370 Yet another map fix
  maps/z1.dmm
Labels: Map Edit

#369 [hotfix] пофиксил пропавшие пиксели в перчатках
  icons/mob/hands.dmi
Labels: Sprites

#367 Свап цветов иконок ХУДа научки,охраны,рекуклера,синие ПДА охраны
  icons/mob/hud.dmi
  icons/obj/pda.dmi
Labels: Sprites

#371 bridgefix
  maps/z1.dmm
Labels: Map Edit

#174 Магазинчики
  code/datums/wires/vendshop.dm
  code/game/machinery/constructable_frame.dm
  code/game/machinery/vendshop.dm
  icons/obj/vendshop.dmi
  nano/templates/vendshop.tmpl
  taucetistation.dme
Labels: Feature, Work In Progress

#383 Агреволь чинит свою фигню
  maps/z1.dmm
Labels: Map Edit

#384 yetyetyetanothermapfix
  maps/z1.dmm
Labels: Map Edit

#378 Абузеры должны страдать
  code/modules/locations/centcomm/velocity.dm
  maps/z2.dmm
Labels: Map Edit

#387 SMALLGAY NUCLEAR EMERGENCY
  code/game/gamemodes/nuclear/nuclearbomb.dm
Labels: Priority: CRITICAL

#388 SMALLGAY NUCLEAR EMERGENCY #2
  code/game/gamemodes/nuclear/nuclearbomb.dm
Labels: Priority: CRITICAL

#389 Маг больше не может стрелять поинтбланком
  code/modules/projectiles/gun.dm
Labels: Fix, Merge Ready

#386 Небольшой фикс мусорных труб
  code/modules/recycling/disposal.dm
  code/modules/recycling/sortingmachinery.dm
Labels: Merge Ready

#397 On a clear day you can see my runtime
  code/modules/mob/living/carbon/species.dm
Labels: Priority: High

#398 noonereadsthese
  code/game/area/Space Station 13 areas.dm
  maps/z1.dmm
Labels: Map Edit

#391 Фикс влажной тряпочки
  code/modules/detectivework/footprints_and_rag.dm
Labels: Fix, HONK, Merge Ready

#287 Revert "Revert "Your memes ends here""
  code/__DEFINES/role_preferences.dm
  code/_globalvars/lists/misc.dm
  code/controllers/configuration.dm
  code/datums/mind.dm
  code/game/gamemodes/meme/meme.dm
  code/game/gamemodes/objective.dm
  code/modules/admin/admin.dm
  code/modules/admin/player_panel.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/parasite/meme.dm
  code/modules/mob/living/parasite/parasite.dm
  taucetistation.dme
Labels: Merge Ready

#357 Добавлен раздатчик Space Cleaner'а
  code/modules/reagents/reagent_dispenser.dm
  icons/obj/objects.dmi
Labels: Feature, Merge Ready, Sprites

#403 Изменение 3 причесок
  icons/mob/human_face.dmi
Labels: Merge Ready, Sprites

#345 Odysseus sleeper tweak
  code/game/mecha/equipment/tools/medical_tools.dm
Labels: Merge Ready, Tweak

#405 Фиксим фаер алярм
  code/game/machinery/alarm.dm
Labels: Fix, Merge Ready

#406 GAMMA вместо EXODUS на подах эвакуации
  code/modules/locations/shuttles/pod.dmi
Labels: Sprites

#408 Vietnam is playable again
  code/modules/clothing/head/helmet.dm
Labels: Fix, Merge Ready

#407 Свап цвета охраны и гражданских
  icons/obj/card.dmi
Labels: Merge Ready, Sprites

#412 Фиксим сломаный АПЦ
  code/modules/power/apc.dm
Labels: Fix

#415 Фикс проеба с фиксом АПЦ
  code/modules/power/apc.dm
Labels: Fix

#416 Фиксы гнилого мапинга
  maps/templates/holodeck/courtroom.dmm
  maps/templates/holodeck/picnicarea.dmm
  maps/z1.dmm
  maps/z5.dmm
Labels: Feature, Map Edit, Merge Ready

#418 Быстрофикс быстробага
  maps/z5.dmm
Labels: Map Edit, Merge Ready

#420 Пополнение лодаута персонажа, мелкофиксы
  code/game/machinery/vending.dm
  code/modules/client/character menu/loadout/loadout_clothing.dm
  code/modules/client/character menu/loadout/loadout_hats.dm
  code/modules/clothing/under/miscellaneous.dm
Labels: Merge Ready, Tweak

#421 Скажем нет рантаймам из-за ИИ
  code/datums/wires/_wires.dm
Labels: Merge Ready, Performance

#426 Мелкие фиксы инвентаря
  code/_onclick/hud/screen_objects.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/bible.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/paperwork/photography.dm
Labels: Fix, Merge Ready

#427 Укрепляем защиту Z2
  maps/z2.dmm
Labels: Map Edit

#422 Спейс поды или как всем селом будем их портировать
  code/_onclick/click.dm
  code/modules/spacepods/SP_machynery.dm
  code/modules/spacepods/construction.dm
  code/modules/spacepods/equipment.dm
  code/modules/spacepods/lock_buster.dm
  code/modules/spacepods/parts.dm
  code/modules/spacepods/spacepoddoor.dm
  code/modules/spacepods/spacepods.dm
  icons/goonstation/48x48/pod_construction.dmi
  icons/goonstation/48x48/pods.dmi
  icons/goonstation/pods/pod_parts.dmi
  icons/goonstation/pods/ship.dmi
  icons/vehicles/spacepod.dmi
  sound/effects/engine_alert1.ogg
  sound/effects/engine_alert2.ogg
  taucetistation.dme
Labels: Experimental, Feature, Merge Ready, Sprites

#428 Быстро добавляем файлы пропавшие
  code/modules/mining/mine_items.dm
  icons/obj/doors/1x3blast_hor.dmi
  icons/obj/doors/1x3blast_vert.dmi
Labels: Sprites

#433 Очередные маски в театр...
  code/game/machinery/vending.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/mask.dmi
  icons/obj/clothing/masks.dmi
Labels: Feature, Sprites, Tweak

#434 Крутим поды, исправляя разные баги
  code/modules/spacepods/construction.dm
  code/modules/spacepods/equipment.dm
  code/modules/spacepods/spacepoddoor.dm
  code/modules/spacepods/spacepods.dm
Labels: Fix

#435 rnd-pod tweaks
  code/game/area/Space Station 13 areas.dm
  maps/z1.dmm
Labels: Map Edit

#436 Revert "rnd-pod tweaks"
  code/game/area/Space Station 13 areas.dm
  maps/z1.dmm
Labels: Map Edit

#438 Синий цвет подсветки для консолей Дозора
  code/game/machinery/computer/camera.dm
  code/game/machinery/computer/prisoner.dm
  code/game/machinery/computer/security.dm
  code/modules/detectivework/detective_work.dm
Labels: Fix, Merge Ready

#439 Еще изменения для спейс подов
  code/__DEFINES/machinery.dm
  code/game/objects/effects/effect_system.dm
  code/modules/research/designs.dm
  code/modules/spacepods/SP_machynery.dm
  code/modules/spacepods/equipment.dm
  code/modules/spacepods/parts.dm
  code/modules/spacepods/spacepoddoor.dm
  code/modules/spacepods/spacepods.dm
  icons/effects/ion_effect_x64.dmi
  icons/obj/doors/spacepod_blast_doors/1x2blast_hor.dmi
  icons/obj/doors/spacepod_blast_doors/1x2blast_vert.dmi
  icons/obj/doors/spacepod_blast_doors/1x3blast_hor.dmi
  icons/obj/doors/spacepod_blast_doors/1x3blast_vert.dmi
  icons/obj/doors/spacepod_blast_doors/1x4blast_hor.dmi
  icons/obj/doors/spacepod_blast_doors/1x4blast_vert.dmi
  icons/obj/doors/spacepod_blast_doors/blast_door.dmi
Labels: Fix, Merge Ready, Sprites

#440 Небольшие изменения в предметах Синдиката и..
  code/datums/uplinks_items.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/revolver.dm
Labels: Balance, Merge Ready, Tweak

#441 Респрайт милитари подов
  icons/48x48/pods.dmi
Labels: Merge Ready, Sprites

#444 Фикс возможности выбора бороды для женских персонажей ОБР
  code/game/response_team.dm
Labels: Fix, Merge Ready

#445 Фикс шлема нинжы и еды
  code/modules/clothing/spacesuits/ninja.dm
Labels: Fix, Merge Ready

#447 Фиксим пропавший href в АПЦ
  code/modules/power/apc.dm
Labels: Fix, Merge Ready

#450 Барбершоп для хвостатых
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites

#454 seedfixes
  icons/obj/hydroponics/seeds.dmi
Labels: Fix, Merge Ready, Sprites

#455 Velocity signs bugfix
  code/modules/locations/centcomm/velocity.dm
  icons/obj/decals.dmi
Labels: Fix, Merge Ready, Sprites

#453 Фикс подбора батарейки у открытого АПЦ
  code/modules/power/apc.dm
Labels: Fix, Merge Ready

#451 Теперь можно залезать на стойки(RACK)
  code/game/objects/structures/tables_racks.dm
Labels: Merge Ready, Tweak

#457 Гранатомёт можно повесить на спину и броню
  code/modules/clothing/spacesuits/captain.dm
  code/modules/clothing/suits/armor.dm
  code/modules/reagents/grenade_launcher.dm
Labels: Merge Ready, Tweak

#462 Фикс magnectic gripper
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
Labels: Fix, Merge Ready

#465 sodadispenser fix
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Fix, Merge Ready

#468 Некоторые фиксы для Тихеон подъехали.
  code/_onclick/click.dm
  code/_onclick/telekinesis.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/doors/door.dm
  code/game/objects/items.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/gift_wrappaper.dm
  code/game/objects/items/weapons/implants/implantpad.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/items/weapons/tools.dm
  code/game/objects/structures/coathanger.dm
  code/game/sound.dm
  code/modules/holidays/new_year/presents.dm
  code/modules/mob/death.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/inventory.dm
  code/modules/mob/language.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/paperwork/photography.dm
  code/modules/power/lighting.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
Labels: Fix, Merge Ready

#467 Guest Terminal Tweaks
  code/game/machinery/computer/guestpass.dm
  icons/obj/card.dmi
  icons/obj/computer.dmi
Labels: Fix, Merge Ready, Sprites, Tweak

#469 Three Girls One Moustahce
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Feature, Merge Ready, Sprites, Tweak

#118 [WIP]Thunderfield
  code/__DEFINES/is_helpers.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/other_mobs.dm
  code/_onclick/hud/vrhuman.dm
  code/datums/mind.dm
  code/datums/uplinks_items.dm
  code/game/area/Space Station 13 areas.dm
  code/game/machinery/constructable_frame.dm
  code/game/objects/items/devices/uplinks.dm
  code/game/turfs/unsimulated/floor.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/security levels/security levels.dm
  code/modules/thunderfield2562/thunderfield.dm
  code/modules/thunderfield2562/thunderfield_gamepod.dm
  code/modules/thunderfield2562/thunderfield_people.dm
  icons/mob/screen_vrhuman.dmi
  icons/obj/items.dmi
  icons/obj/machines/gamepod.dmi
  icons/turf/areas.dmi
  maps/z1.dmm
  maps/z2.dmm
  taucetistation.dme
Labels: Feature, Map Edit, Sprites, YoloMerge Ready

#474 thundermap
  code/game/turfs/unsimulated/floor.dm
  code/modules/media/jukebox.dm
  maps/z1.dmm
  maps/z2.dmm
Labels: Map Edit

#477 Убрал логирование на тандере
  code/_onclick/item_attack.dm
  code/game/objects/items.dm
  code/game/turfs/unsimulated/floor.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/mob_grab.dm
  code/modules/projectiles/projectile.dm
  code/modules/thunderfield2562/thunderfield_gamepod.dm
  code/modules/thunderfield2562/thunderfield_people.dm
Labels: Fix, Merge Ready

#479 БыстроFixes #472
  code/datums/uplinks_items.dm
  code/modules/thunderfield2562/thunderfield_gamepod.dm
Labels: Fix, Merge Ready

#480 telepathy tweaks
  code/_onclick/click.dm
  code/_onclick/item_attack.dm
  code/_onclick/other_mobs.dm
  code/_onclick/telekinesis.dm
  code/game/objects/items/weapons/RCD.dm
  code/game/objects/items/weapons/RSF.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/mob/language.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/ian/ian.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/typing_indicator.dm
  code/modules/paperwork/filingcabinet.dm
  icons/mob/talk.dmi
Labels: Sprites, Tweak

#481 Fixes #475
  code/game/gamemodes/autotraitor/autotraitor.dm
  code/game/gamemodes/objective.dm
Labels: Fix, Merge Ready

#483 Teletyping animation tweak.
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/typing_indicator.dm
  icons/mob/talk.dmi
Labels: Sprites

#484 Ещё один ПР про телепатию...
  code/_onclick/telekinesis.dm
  code/game/machinery/OpTable.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/newscaster.dm
  code/game/objects/items/robot/robot_parts.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/mob_movement.dm
  code/modules/mob/typing_indicator.dm
  code/modules/research/xenoarchaeology/tools/tools_coresampler.dm
Labels: Fix, Merge Ready, Sprites, Tweak

#490 Фиксы тандерфилда
  code/_onclick/hud/vrhuman.dm
  code/_onclick/item_attack.dm
  code/datums/uplinks_items.dm
  code/game/objects/items/devices/uplinks.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/security levels/security levels.dm
  code/modules/thunderfield2562/thunderfield_gamepod.dm
  code/modules/thunderfield2562/thunderfield_people.dm
  icons/mob/screen_vrhuman.dmi
Labels: Balance, Fix, Merge Ready, Sprites

#488 Генетика, КД на клики, дурацкие столы ненавижу их помогите.
  code/_onclick/click.dm
  code/_onclick/item_attack.dm
  code/_onclick/other_mobs.dm
  code/_onclick/telekinesis.dm
  code/game/dna/dna2.dm
  code/game/gamemodes/changeling/powers/absorb.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/ian/ian.dm
  code/modules/mob/living/carbon/species.dm
Labels: Fix, Merge Conflict

#494 Glowing tycheons: beggining.
  code/_onclick/click.dm
  code/_onclick/telekinesis.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/Chemistry-Colours.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/chemistry/Chemistry-Holder.dm
  code/modules/reagents/reagent_containers/food/glowsticks.dm
Labels: Merge Ready, Tweak

#497 Возможность телепатией слушать хайвчаты, видеть эмоуты.
  code/_onclick/click.dm
  code/game/gamemodes/cult/cult_datums.dm
  code/game/gamemodes/shadowling/shadowling_abilities.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/mob/emote.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/species.dm
Labels: Fix, Merge Ready

#496 Фикс лишних пикселей на подах
  icons/48x48/pods.dmi
Labels: Fix, Merge Ready, Sprites

#506 теленёрфы.
  code/_onclick/telekinesis.dm
  code/game/jobs/access.dm
Labels: Fix, Merge Ready

#507 Очередные багфиксы багодрома
  code/modules/thunderfield2562/thunderfield_gamepod.dm
  code/modules/thunderfield2562/thunderfield_people.dm
Labels: Fix, Merge Ready

#509 Очередная заглушка на логи тандера
  code/_onclick/item_attack.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
Labels: Fix, Merge Ready

#510 Спрайты скафандров ХОСа, СМО и новый ящик для скафандров
  code/game/objects/closets/suit_storage_closet.dm
  icons/mob/head.dmi
  icons/mob/species/skrell/helmet.dmi
  icons/mob/species/skrell/suit.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/unathi/helmet.dmi
  icons/mob/species/unathi/suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/species/skrell/hats.dmi
  icons/obj/clothing/species/skrell/suits.dmi
  icons/obj/clothing/species/tajaran/hats.dmi
  icons/obj/clothing/species/tajaran/suits.dmi
  icons/obj/clothing/species/unathi/hats.dmi
  icons/obj/clothing/species/unathi/suits.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/suitcloset.dmi
  taucetistation.dme
Labels: Sprites

#511 Гендеры у ксеноты, тихеоне-шизофреники, телеКД.
  code/_onclick/click.dm
  code/_onclick/telekinesis.dm
  code/game/gamemodes/abduction/machinery/experiment.dm
  code/game/objects/structures/extinguisher.dm
  code/game/objects/structures/mirror.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/character menu/general.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/syndicate.dm
  code/modules/clothing/under/ties.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/projectiles/projectile/change.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/reagents/Chemistry-Reagents.dm
  icons/mob/human_face.dmi
Labels: Sprites

#512 Глазки закрывай.(Фиксы)
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/species.dm
Labels: Fix, Merge Ready

#513 Теленёрфы 2.0.
  code/_onclick/telekinesis.dm
  code/game/atoms_movable.dm
  code/game/dna/genes/powers.dm
  code/game/machinery/OpTable.dm
  code/game/objects/effects/chemsmoke.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/ian/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/research/xenoarchaeology/tools/bunsen_burner.dm
Labels: Balance, Merge Ready

#523 Фикс спрайтов от омеги
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/uniform_fat.dmi
Labels: Fix, Merge Ready, Sprites

#522 Защита от телепатии.
  code/_onclick/telekinesis.dm
  code/game/gamemodes/abduction/abduction_gear.dm
  code/game/gamemodes/changeling/powers/mutations.dm
  code/game/gamemodes/cult/cult_items.dm
  code/game/objects/WalterJ_Items_Pack/NT PMC/WJ_NT_PMC.dm
  code/game/objects/WalterJ_Items_Pack/RED FACTION RIG/WJ_Red_Faction_Rig.dm
  code/game/objects/WalterJ_Items_Pack/WERMAHT UNIFORMS/WJ_Wermaht_uniforms.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/client/asset_cache.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/spacesuits/Skafandr_kosmicheskiy.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/clothing/spacesuits/captain.dm
  code/modules/clothing/spacesuits/ert.dm
  code/modules/clothing/spacesuits/globose.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/spacesuits/ninja.dm
  code/modules/clothing/spacesuits/rig.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/utility.dm
  code/modules/clothing/suits/wiz_robe.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/syndicate.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/css/fonts/balanced_font.eot
  code/modules/goonchat/browserassets/css/fonts/balanced_font.ttf
  code/modules/goonchat/browserassets/css/fonts/horror_font.eot
  code/modules/goonchat/browserassets/css/fonts/horror_font.otf
  code/modules/holidays/new_year/clothing.dm
  code/modules/mob/language.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/metroid/metroid.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_grab.dm
  code/modules/mob/mob_movement.dm
  code/modules/paperwork/paper.dm
  code/modules/power/lighting.dm
  code/modules/recycling/disposal.dm
  code/modules/research/xenoarchaeology/tools/anomaly_suit.dm
Labels: Feature, Fix, Merge Ready, Performance
