Repository GammaStation/Gamma-Station, pull requests merged in 2018-08, with the labels that each got.

#95 Респрайт еганов и Л-10 от всеми любимого ящера.
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
Labels: Sprites

#101 Moretimeinthehouse
  code/_globalvars/lists/misc.dm
Labels: Balance

#104 Ехидные пИИ теперь не смогут засечь нюку по ПДА
  code/modules/mob/living/silicon/pai/software.dm
Labels: Fix

#105 Картечь снова работает
  code/game/mecha/equipment/weapons/weapons.dm
  code/modules/projectiles/firing.dm
  code/modules/projectiles/projectile.dm
Labels: Fix

#121 Маски четверки из payday
  code/game/machinery/vending.dm
  code/modules/clothing/masks/gasmask.dm
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/mask.dmi
  icons/obj/clothing/masks.dmi
Labels: Sprites

#128 Личные риги для СМО и ХоСа
  code/game/machinery/vending.dm
  code/game/objects/items/devices/modkit.dm
  code/modules/clothing/spacesuits/rig.dm
  icons/mob/head.dmi
  icons/mob/species/skrell/helmet.dmi
  icons/mob/species/skrell/suit.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/unathi/helmet.dmi
  icons/mob/species/unathi/suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/species/skrell/hats.dmi
  icons/obj/clothing/species/skrell/suits.dmi
  icons/obj/clothing/species/tajaran/hats.dmi
  icons/obj/clothing/species/tajaran/suits.dmi
  icons/obj/clothing/species/unathi/hats.dmi
  icons/obj/clothing/species/unathi/suits.dmi
  icons/obj/clothing/suits.dmi
  maps/z1.dmm
Labels: Feature, Map Edit, Sprites, Tweak

#131 Картоправки и новый советский спутник
  maps/z1.dmm
  maps/z4.dmm
Labels: Map Edit

#120 Исправлено логирование проджектайлов
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/mob_helpers.dm
  code/modules/projectiles/projectile.dm
Labels: Fix

#103 Запрет на использование ряда предметов живностью
  code/game/objects/items/devices/flash.dm
  code/game/objects/items/devices/remote_device.dm
  code/game/objects/items/weapons/teleportation.dm
Labels: Tweak, Work In Progress

#140 Уменьшил weaken у болы
  code/defines/obj/weapon.dm
Labels: Balance

#147 Скафандр нинзди получил существенный бафф к защите от лазеров.
  code/modules/clothing/spacesuits/ninja.dm
Labels: Balance

#155 Воруй&Кради
  code/controllers/subsystem/jobs.dm
  code/datums/spells/conjure.dm
  code/game/gamemodes/blob/blobs/factory.dm
  code/game/gamemodes/shadowling/shadowling_abilities.dm
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/paint.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/language.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/mob/living/living.dm
  code/modules/reagents/Chemistry-Reagents-Antidepressants.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/research/xenoarchaeology/machinery/coolant.dm
  code/modules/virus2/antibodies.dm
Labels: Feature, Fix, Tweak

#158 Разблокированы интеркоммы на диджейке
  maps/z4.dmm
Labels: Map Edit, Tweak

#159 Meathook fix
  code/_onclick/item_attack.dm
  code/game/objects/items/weapons/kitchen.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix

#161 Ревплакаты 2.0
  code/datums/uplinks_items.dm
  code/game/objects/effects/decals/contraband.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  icons/obj/contraband.dmi
Labels: Feature, Sprites
