Repository GammaStation/Gamma-Station, pull requests merged in 2019-07, with the labels that each got.

#724 Сообщения атак простых мобов
  code/game/gamemodes/blob/blobs/factory.dm
  code/game/gamemodes/changeling/headcrab.dm
  code/game/gamemodes/events/cellular_biomass/biome_bluespace.dm
  code/game/gamemodes/events/cellular_biomass/biome_meat.dm
  code/game/gamemodes/shadowling/ascendant_shadowling.dm
  code/game/machinery/bots/bots.dm
  code/game/machinery/portable_turret.dm
  code/game/mecha/mecha.dm
  code/modules/jungle/jungle_animals.dm
  code/modules/mining/equipment_locker.dm
  code/modules/mining/monsters.dm
  code/modules/mob/living/carbon/alien/alien_defense.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/ian/ian.dm
  code/modules/mob/living/carbon/metroid/metroid.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/borer.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/friendly/lizard.dm
  code/modules/mob/living/simple_animal/friendly/spiderbot.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/creature.dm
  code/modules/mob/living/simple_animal/hostile/cyber_horror.dm
  code/modules/mob/living/simple_animal/hostile/faithless.dm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/living/simple_animal/hostile/pirate.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  code/modules/mob/living/simple_animal/hostile/russian.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/mob/living/simple_animal/hostile/tree.dm
  code/modules/mob/living/simple_animal/hulk.dm
  code/modules/mob/living/simple_animal/shade.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/simple_animal/special/scp.dm
  code/modules/mob/living/simple_animal/worm.dm
  code/modules/research/xenoarchaeology/genetics/prehistoric_animals.dm
  code/modules/spacepods/spacepods.dm
Labels: Tweak

#725 Добавляет три химиката для помощи в стабилизации пациентов.
  code/game/objects/items/weapons/autoinjectors.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/organs/blood.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/chemistry/Chemistry-Holder.dm
  code/modules/reagents/chemistry/reagents/medical_reagents.dm
  code/modules/reagents/chemistry/recipes/medicines.dm
  icons/obj/syringe.dmi
Labels: Feature, Merge Ready

#726 Forcing vomit with fingers, reagents and punches.
  code/datums/diseases/advance/symptoms/vomit.dm
  code/modules/mining/equipment_locker.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob_grab.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/chemistry/reagents/medical_reagents.dm
  code/modules/reagents/chemistry/recipes/medicines.dm
Labels: Feature, Merge Ready

#728 Preference to toggle scans to chat or into a window.
  code/game/objects/items.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
Labels: Merge Ready, Tweak

#730 Handheld bodypart scanner.
  code/game/machinery/adv_med.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/research/designs.dm
  icons/obj/bodypart_scanner.dmi
Labels: Feature, Merge Ready
