Repository GammaStation/Gamma-Station, pull requests merged in 2019-03, with the labels that each got.

#678 Респрайт дефолтного армора,второго сета ХоСа
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Merge Ready, Sprites

#679 Новые плейлисты в джукбокс
  code/modules/media/jukebox.dm
Labels: Merge Ready, PLATINUM

#682 New Brand OM36
  code/datums/uplinks_items.dm
  code/game/objects/random/random_syndie.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
  sound/weapons/guns/ak74_fire.ogg
  sound/weapons/guns/ak74_reload.ogg
  sound/weapons/guns/om36f.ogg
  sound/weapons/guns/om36r.ogg
Labels: Merge Ready, Sprites

#680 Молочко, скреллы и метаболизм
  code/__DEFINES/mob.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/ian/life.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/species.dm
  code/modules/reagents/chemistry/Chemistry-Holder.dm
Labels: Feature, Revert Candidate, Tweak

#683 Спрайтодобавления
  icons/mob/back.dmi
  icons/mob/belt_mirror.dmi
Labels: Merge Ready, Sprites, Tweak

#686 Новые инструменты педальной тирании
  code/__DEFINES/admin.dm
  code/__DEFINES/misc.dm
  code/datums/browser.dm
  code/datums/repositories/_defines.dm
  code/datums/repositories/client.dm
  code/datums/repositories/repository.dm
  code/datums/repositories/~defines.dm
  code/modules/admin/admin.dm
  code/modules/admin/ticket.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/admin/verbs/staffhelp.dm
  code/modules/client/client procs.dm
  code/modules/mentor/mentorhelp.dm
  taucetistation.dme
Labels: Admin, Experimental, Merge Ready, Test Merge, enhancement

#685 Shadowling clone fix
  code/modules/mob/living/carbon/species.dm
Labels: Fix, Merge Ready

#687 Тикетоправки
  code/modules/admin/verbs/adminpm.dm
Labels: Admin, Fix

#689 Фиксим спам в АХ, удаляем аколл
  code/modules/admin/verbs/adminhelp.dm
  code/modules/ext_scripts/slack_admin_call.dm
  taucetistation.dme
Labels: Admin, Fix, Merge Ready, Revert / Removal
