Repository GammaStation/Gamma-Station, pull requests merged in 2019-01, with the labels that each got.

#654 Телепортоабуз NO MORE 2
  code/controllers/subsystem/shuttles.dm
  code/modules/cargo/console.dm
Labels: Fix, exploit

#650 Goonchat
  code/__DEFINES/misc.dm
  code/__DEFINES/sound.dm
  code/__HELPERS/text.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/weapons/transparant.dm
  code/game/objects/structures/chalkboard.dm
  code/game/verbs/ooc.dm
  code/modules/admin/admin.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/admin/verbs/adminsay.dm
  code/modules/admin/verbs/playsound.dm
  code/modules/admin/verbs/staffhelp.dm
  code/modules/client/asset_cache.dm
  code/modules/client/client defines.dm
  code/modules/client/client procs.dm
  code/modules/client/preferences_toggles.dm
  code/modules/error_handler_js/error_handler.dm
  code/modules/error_handler_js/error_handler.js
  code/modules/ext_scripts/slack_admin_call.dm
  code/modules/goonchat/browserOutput.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/css/emoji.css
  code/modules/goonchat/browserassets/css/emoji/dildo.gif
  code/modules/goonchat/browserassets/css/emoji/zolotoi_digol.gif
  code/modules/goonchat/browserassets/html/browserOutput.html
  code/modules/goonchat/browserassets/js/browserOutput.js
  code/modules/mob/dead/observer/say.dm
  code/modules/mob/say.dm
  interface/skin.dmf
  taucetistation.dme
Labels: Test Merge

#659 Gulag-fluff
  code/game/objects/effects/decals/contraband.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/structures/gulag.dm
  code/game/objects/structures/signs/_signs.dm
  icons/obj/contraband.dmi
  icons/obj/decals.dmi
  icons/obj/lighting.dmi
  icons/obj/structures/gulag.dmi
  taucetistation.dme
Labels: Merge Ready, Sprites

#657 Added logging for the toilet
  code/game/objects/structures/watercloset.dm
Labels: ! NEEDS REVIEW !, Fix
