Repository GammaStation/Gamma-Station, pull requests merged in 2019-06, with the labels that each got.

#717 Больше вендоматов для крафта и небольшая коррекция цен.
  code/game/machinery/constructable_frame.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/vending_items.dm
  code/modules/cargo/packs.dm
  icons/obj/vending.dmi
Labels: Feature, Merge Ready

#719 Стелс риг для ОБР
  code/modules/clothing/spacesuits/ert.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  maps/z2.dmm
Labels: Experimental, Feature

#720 Новые спрайты вендоматов
  icons/obj/vending.dmi
Labels: Merge Ready, Resprite

#721 Проигрывание зонального эмбиента
  code/game/area/Space Station 13 areas.dm
  code/game/area/areas.dm
  code/modules/client/client defines.dm
  code/modules/mining/mine_areas.dm
Labels: Revert / Removal, Sound, Tweak

#722 Новые спрайты различных терминалов
  code/modules/power/apc.dm
  icons/obj/airlock_machines.dmi
  icons/obj/power.dmi
  icons/obj/stationobjs.dmi
  icons/obj/terminals.dmi
Labels: Resprite
