Repository GammaStation/Gamma-Station, pull requests merged in 2019-02, with the labels that each got.

#665 rigi_aga
  icons/mob/head.dmi
  icons/mob/species/skrell/helmet.dmi
  icons/mob/species/skrell/suit.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/unathi/helmet.dmi
  icons/mob/species/unathi/suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/species/skrell/hats.dmi
  icons/obj/clothing/species/skrell/suits.dmi
  icons/obj/clothing/species/tajaran/hats.dmi
  icons/obj/clothing/species/tajaran/suits.dmi
  icons/obj/clothing/species/unathi/hats.dmi
  icons/obj/clothing/species/unathi/suits.dmi
  icons/obj/clothing/suits.dmi
Labels: Resprite

#666 gunsgunsguns
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
Labels: Resprite

#669 Fixed typo
  code/game/objects/items.dm
Labels: Fix, Merge Ready

#670 Hostile animals now eat spacepods
  code/_globalvars/lists/objects.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/spacepods/spacepods.dm
Labels: Feature, Revert Candidate, YoloMerge Ready

#673 Респрайт ПП нюкеров
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/obj/gun.dmi
Labels: Merge Ready, Resprite

#664 Возвращение блудного рефактора
  code/__DEFINES/chemistry.dm
  code/__DEFINES/mob.dm
  code/datums/spells/conjure.dm
  code/game/gamemodes/blob/blobs/factory.dm
  code/game/gamemodes/shadowling/shadowling_abilities.dm
  code/game/machinery/bees_items.dm
  code/game/objects/items/weapons/paint.dm
  code/modules/economy/Events.dm
  code/modules/reagents/Chemistry-Colours.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/reagents/Chemistry-Readme.dm
  code/modules/reagents/Chemistry-Reagents-Antidepressants.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/chemistry/Chemistry-Colours.dm
  code/modules/reagents/chemistry/Chemistry-Holder.dm
  code/modules/reagents/chemistry/machinery/coda_dispencer.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/medical_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/poo_reagents.dm
  code/modules/reagents/chemistry/reagents/pyrotecnics_reagents.dm
  code/modules/reagents/chemistry/reagents/toxic_reagents.dm
  code/modules/reagents/chemistry/recipes/food_drinks.dm
  code/modules/reagents/chemistry/recipes/other.dm
  code/modules/reagents/chemistry/weaponry/grenade_launcher.dm
  code/modules/reagents/dartgun.dm
  code/modules/reagents/grenade_launcher.dm
  code/modules/reagents/syringe_gun.dm
  code/modules/research/xenoarchaeology/machinery/coolant.dm
  code/modules/virus2/antibodies.dm
  taucetistation.dme
Labels: Revert Candidate, Tweak

#674 Исправление канала новостей ньюскастера
  code/controllers/subsystem/economy.dm
Labels: Fix, Merge Ready

#675 Проводку починили
  maps/z1.dmm
Labels: Map Edit, YoloMerge Ready

#677 Респрайт охранки от ВальтераЖе
  icons/mob/back.dmi
  icons/mob/belt.dmi
  icons/mob/feet.dmi
  icons/mob/hands.dmi
  icons/mob/head.dmi
  icons/mob/inhands/guns_lefthand.dmi
  icons/mob/inhands/guns_righthand.dmi
  icons/mob/mask.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_fat.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/gun.dmi
Labels: Merge Ready, Sprites

#676 Ребаланс цен карго
  code/modules/cargo/exports/large_objects.dm
  code/modules/cargo/exports/sheets.dm
  code/modules/cargo/exports/tools.dm
  code/modules/cargo/exports/weapons.dm
  code/modules/cargo/packs.dm
Labels: Balance, Merge Ready, Tweak
