Repository GammaStation/Gamma-Station, pull requests merged in 2019-05, with the labels that each got.

#708 Сглаживание на чёрные шаттлостены
  code/game/machinery/doors/unpowered.dm
  code/game/objects/structures/shuttle_structures.dm
  code/game/turfs/simulated/walls_shuttle.dm
  icons/obj/structures/shuttle/window_black.dmi
  icons/turf/shuttle_black.dmi
  maps/z2.dmm
Labels: Map Edit, Sprites

#713 Новый спрайт выключателя
  icons/obj/power.dmi
Labels: Sprites

#709 Возможность сбора и подключения шаттерсов к кнопкам.
  code/game/machinery/door_control.dm
  code/game/machinery/doors/shutters.dm
  code/game/objects/items/devices/multitool.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack.dm
  code/game/turfs/simulated/walls.dm
Labels: Feature, Merge Ready, Tweak

#712 Возможность покраски плитки, добавление красящего аппарата в карго.
  code/__DEFINES/construction.dm
  code/game/objects/items/weapons/airlock_painter.dm
  code/modules/cargo/packs.dm
Labels: Feature, Merge Ready, Sprites

#710 Постройка бодисканнера, консоли, крафт каталок, инвалидного кресла.
  code/game/machinery/adv_med.dm
  code/game/machinery/constructable_frame.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/research/designs.dm
Labels: Feature

#711 Морг слабы, мешки для трупов из пластика.
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/structures/morgue.dm
Labels: Feature

#716 Контроллеры шлюзов
  code/game/machinery/embedded_controller/airlock_program.dm
  code/game/machinery/embedded_controller/embedded_controller_base.dm
  icons/obj/airlock_machines.dmi
Labels: Feature, Resprite
