Repository GammaStation/Gamma-Station, pull requests merged in 2019-09, with the labels that each got.

#733 Fixing weird fonts in windowed analyzer.
  code/game/objects/items.dm
Labels: Fix, Merge Ready

#734 Фикс шлема + фикс профессии
  code/game/jobs/job/outpost/general.dm
  code/modules/warfare/gear.dmi
Labels: Fix

#735 Набор фиксов
  code/game/gamemodes/survival/survival.dm
  code/modules/mob/living/simple_animal/hostile/hellspawn/hellspawn.dm
  code/modules/planets/volcano/turfs.dm
  maps/RandomZLevels/zresearchlabs.dmm
  maps/outpost/backup/backup/z1.dmm
  maps/outpost/backup/deismos.dmm
  maps/outpost/backup/phobos.dmm
  maps/outpost/backup/sandbox.dmm
  maps/outpost/backup/z1.dmm
  maps/outpost/backup/z2.dmm
  maps/outpost/backup/z3.dmm
  maps/outpost/big.dmm
  maps/outpost/deismos.dmm
  maps/outpost/outpost/z1.dmm
  maps/outpost/outpost/z2.dmm
  maps/outpost/phobos.dmm
  maps/outpost/sandbox.dmm
  maps/outpost/shuttle1.dmm
  maps/outpost/templates/patrol_base.dmm
  maps/outpost/z1.dmm
  maps/outpost/z2.dmm
  maps/outpost/z3.dmm
  maps/z2.dmm
Labels: Fix

#736 Ещё правки
  code/game/gamemodes/survival/enemies.dm
  code/game/gamemodes/survival/survival.dm
  code/modules/power/geothermal/geothermal.dm
  maps/outpost/z1.dmm
Labels: Balance

#737 Отключаем режим ультранасилия
  code/game/gamemodes/survival/survival.dm
Labels: Balance

#738 Ультранасилие обратно, плюс разблокирована профа
  code/game/gamemodes/survival/supply_mechanic.dm
  code/game/gamemodes/survival/survival.dm
  code/game/jobs/job/outpost/combat.dm
  maps/outpost/z1.dmm
Labels: Balance
